<?php

namespace Core\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * radcheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class radcheckRepository extends EntityRepository
{
}
