<?php

namespace Core\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ssidmacauthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ssidmacauthRepository extends EntityRepository
{
}
